# Generated by Django 5.0.1 on 2024-04-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='User',
            new_name='usuario',
        ),
    ]
