# Generated by Django 5.0.1 on 2024-04-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
