# Generated by Django 5.0.1 on 2024-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alumnos_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='nombre',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='profesores',
            name='nombre',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
