# Generated by Django 5.0.1 on 2024-09-08 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_laboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='laboratorio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.laboratorio'),
        ),
    ]
