# Generated by Django 5.0.1 on 2024-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_reserva_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='bloque',
            field=models.CharField(max_length=20),
        ),
    ]
