# Generated by Django 5.0.1 on 2024-09-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_laboratorio_bloque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='cod_lab',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
