# Generated by Django 5.0.1 on 2024-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_laboratorio_cod_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.TextField(unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
