# Generated by Django 5.0.1 on 2024-10-23 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_meses_alter_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 10, 23)),
            preserve_default=False,
        ),
    ]
