# Generated by Django 5.0.1 on 2024-10-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_reserva_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='capacidad_total',
            field=models.IntegerField(default=0),
        ),
    ]
