# Generated by Django 5.0.1 on 2024-11-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_reserva_hora_fin_reserva_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(),
        ),
    ]
